### ISSUE TITLE
Question about link

### ISSUE THREAD

**Issue by Sandeep-source** [aachal28/Awesome-web-development-resources#1]
Link in this section
https://github.com/aachal28/Awesome-web-development-resources#ui-design-inspirations

are misplaced or just not completed yet?

@aachal28

**Comment by aachal28** [comment]
> Link in this section https://github.com/aachal28/Awesome-web-development-resources#ui-design-inspirations
> 
> are misplaced or just not completed yet?
> 
> @aachal28

this list was not completed yet i have to add links.

**Comment by Sandeep-source** [comment]
@aachal28 
Is contributions to this repo allowed ?

**Comment by aachal28** [comment]
> @aachal28 Is contributions to this repo allowed ?

yeah ,If you want to contribute, you can.
